image:
  repository: wavefronthq/wavefront-hpa-adapter
  tag: 0.9.3
  pullPolicy: IfNotPresent

apiserver:
  # Wavefront url of the form https://INSTANCE.wavefront.com
  # wavefrontURL: https://INSTANCE.wavefront.com

  # Wavefront API token with permissions to query for points
  # wavefrontToken: 12345678-90ab-cdef-0123-4567890abcde

  # Metrics under this prefix are exposed in the custom metrics API.
  metricPrefix: kubernetes

  # Interval at which to fetch the list of custom metric names from Wavefront
  metricRelistInterval: 10m

  # one of info, debug, warn or trace
  logLevel: debug

  # List wavefront queries to transform into custom metrics
  # https://github.com/wavefrontHQ/wavefront-kubernetes-adapter/blob/master/pkg/config/config.go
  rules:
    - query: 'ts(azure.compute.vm.percentage.cpu)'
      name: azure.vm.cpu
    - query: 'ts(aws.sqs.approximatenumberofmessagesvisible)'
      name: aws.sqs.messagesvisible
