apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wavefront-kubernetes-adapter.fullname" . }}-external-metrics-reader
  labels:
{{ include "wavefront-kubernetes-adapter.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "wavefront-kubernetes-adapter.fullname" . }}-external-metrics-reader
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
